---
profile: personal
region: us-east-1
iam:
  role_name: KinesisSampleRole
  role_policy: AWSLambdaKinesisExecutionRole
lambda:
  name: KinesisSample
  zipfile_name: KinesisSample.zip
  description: Testing Kinesis Lambda handler
  path: ProcessKinesisRecords.js
  handler: ProcessKinesisRecords.handler
  runtime: nodejs
  memory_size: 128
  timeout: 3
  event_sources:
    -
      arn: arn:aws:kinesis:us-east-1:084307701560:stream/lambdastream
      starting_position: TRIM_HORIZON
      batch_size: 100
  test_data: input.json
  